### ISSUE TITLE
muparser - library needed for calculator_pi

### ISSUE THREAD

**Issue by Rasbats** [leamas/opencpn-libs#1]
calculator_pi is here:
[https://github.com/Rasbats/calculator_pi](https://github.com/Rasbats/calculator_pi)

This uses the muparser library:
[https://github.com/beltoforion/muparser](https://github.com/beltoforion/muparser)

The plugin compiles on all OS but only works on Windows. The plugin runs but it is not linking with the library on other OS?
The muparser library has had a lot of changes since the first calculator_pi.
Could you add the muparser library to opencpn-libs?

Thanks.

**Comment by leamas** [comment]
Might be able to look into this during this week. It is *probably* trivial as long as it not depends on other libraries.

**Comment by leamas** [comment]
Done: https://github.com/Rasbats/calculator_pi/pull/8

**Comment by Rasbats** [comment]
Many thanks. Testing later this morning.
