### ISSUE TITLE
N2KParser in opencpn-libs?

### ISSUE THREAD

**Issue by douwefokkema** [leamas/opencpn-libs#16]
Plugins that use N2k input will need N2KParser (OpenCPN/libs). Is opencpn-libs the right location for this? If so, it should be added. If not where should it be located so that the plugin has access. Currently dashboard_pi is using N2Kparser, but dashboard_pi is compiled together with O itself, no problem there.

**Comment by leamas** [comment]
It is definitely the right place. I will try to handle this in the upcoming days.

If you are in a hurry you could make a local copy in libs/ and use that for the time being.

EDIT: Thanks for  good input!

**Comment by leamas** [comment]
I have added it  without any checks to the devel branch. If you are fluent in handling git submodules you should be able to update your own copy of opencpn-libs to the devel branch to get things rolling.

My plan is to keep it here some days for testing before merging it into main.

**Comment by douwefokkema** [comment]
Compiling fine now, after a "git submodule update --remote --merge opencpn-libs". Thanks.
