### ISSUE TITLE
.DS_Store needs to be added to the .gitignore file for this repository

### ISSUE THREAD

**Issue by antipole2** [leamas/opencpn-libs#17]
MacOS frequently creates a local hidden file `.DS_Store`.  GitHub showsit  as a changed file needing updating, which we cannot do without making a branch and diverging from the gospel.

On my repository, adding  `.DS_Store` to the global `.gitignore` and removing any `.DS_Store` files that have already crept in cures this annoyance.

[See this discussion.](https://stackoverflow.com/questions/11794079/removing-any-ds-store-in-github)

**Comment by leamas** [comment]
Yes, the proper action is IMHO indeed to add .DS_Store to the overall project .gitignore. For that reason I'll close this issue, I don't see the point adding it to a repo which is always used as a subdirectory and besides that does not have any reference to .DS_Store anywhere.

Still, thanks for reporting and sorry for late reply.
