### ISSUE TITLE
sqlite CMakeLists.txt

### ISSUE THREAD

**Issue by Rasbats** [leamas/opencpn-libs#5]
[https://ci.appveyor.com/project/Rasbats/aisrx-pi](https://ci.appveyor.com/project/Rasbats/aisrx-pi)
Using _FindSqlite_ did not work for Win/Linux.
In Win changed it to FindSqlite3 and CMake version upped to 3.14.0. Ok, it built:
[https://ci.appveyor.com/project/Rasbats/aisrx-pi/builds/45302943](https://ci.appveyor.com/project/Rasbats/aisrx-pi/builds/45302943)
But for Linux builds it failed for both FindSqlite and FindSqlite3:
[https://app.circleci.com/pipelines/github/Rasbats/aisRX_pi](https://app.circleci.com/pipelines/github/Rasbats/aisRX_pi)

At one point I mistakenly committed a change to opencpn-libs/sqlite. I think I have undone the change made.

**Comment by Rasbats** [comment]
Reverted to putting the old sqlite directory into _libs_ and adjusting _plugin.cmake_. 

Builds all apart from Flatpak, which we know about (sd3.1.4).

Needed the debian bullseye A32 aisRX build for running the plugin on a Pi 3.

**Comment by leamas** [comment]
> https://ci.appveyor.com/project/Rasbats/aisrx-pi
Using FindSqlite did not work for Win/Linux.

To me, it seems to work just fine. It  tries to locate the system library. When it fails it falls back to using the bundled source. 

Is the link wrong, or are you just worried about the `Could NOT find Sqlite (missing: SQLITE_INCLUDE_DIR SQLITE_LIBRARIES)` message?

**Comment by leamas** [comment]
Ah... found this in the history: 
```
-- Using bundled tinyxml
  CMake Error at opencpn-libs/sqlite/CMakeLists.txt:14 (include):
    include could not find requested file:
  
      FindSqlite
```
We need to handle this better. Wonder how to check if a include file exists...

**Comment by leamas** [comment]
> https://ci.appveyor.com/project/Rasbats/aisrx-pi
Using FindSqlite did not work for Win/Linux.

To me, it seems to work just fine. It  tries to locate the system library. When it fails it falls back to using the bundled source. Is the link wrong, or are you just worried about the

**Comment by Rasbats** [comment]
The FindSqlite3 module was added to CMake 3.14.0. I may not have tested this with a CMake 3.14.0 build for Linux. Does the minimum version of CMake need changing? Reluctant to change the opencpn-libs module for sqlite _CMakeLists.txt_.

**Comment by leamas** [comment]
The core problem here is that it crashes rather than just handles the situation if the cmake file it includes is missing. 

One way could be to probe for if for example FindSqlite exists before actually using it. Another could be to include different files depending on the cmake version. The latter is at least simpler to do. I'll try to patch the  opencpn-libs version and test it against aisrx. Stay tuned...

**Comment by leamas** [comment]
Seems to be fixed for now, closing. Please reopen if problem persists.
