### ISSUE TITLE
msvc-wx32 needed

### ISSUE THREAD

**Issue by Rasbats** [leamas/opencpn-libs#8]
Needed msvc-wx32 for working on other plugins. Please revert #[cbf0f8c](https://github.com/leamas/opencpn-libs/commit/cbf0f8c9a3688a76b83e3b0f4068d104373841b8) if you see problems.

**Comment by leamas** [comment]
NO need for that commit. You are on the wrong branch, opencpn-libs uses devel for the tip (main is just released tags.) These things are already in devel branch.

**Comment by Rasbats** [comment]
UKTides_pi "Updating to latest status" led me into that commit!

Oh ... the main branch produced a wx32 tarball that could be imported into opencpn-leamas.

**Comment by leamas** [comment]
I'll have to reset the main branch... take note of the commit, the branch will be rewinded.

**Comment by leamas** [comment]
main branch reset to 38c2cd i. e. the commit modifying api-{16,17} cbf0f8c is removed completely, also from history.

**Comment by leamas** [comment]
devel merged into main, eventually adding the msvc-wx32 stuff and also a new api-18 directory

**Comment by leamas** [comment]
Issue fixed, closing.
